name: Python CI

on: [push]

jobs:
  test_and_lint:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Run flake8
        # Only run flake8 on py 3.10 to avoid multiple PR comments.
        uses: suo/flake8-github-action@releases/v1
        if: ${{ matrix.python-version == '3.10' }}
        with:
          checkName: 'test_and_lint (3.10)'  # NOTE: this needs to be the same as the job name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test with pytest
        run: |
          pytest
      - name: Run Pub/Sub integration test
        run: |
          cd flow_io/ray_io/integration_test
          ./pubsub_integration.sh