name: Python CI

on: [push]

jobs:
  flake8:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install flake8
      - name: Run flake8
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: 'test_and_lint'  # NOTE: this needs to be the same as the job name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get install redis-server
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Test with pytest
        run: |
          pytest

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          install_components: 'beta,pubsub-emulator'

      - name: Run Pub/Sub integration test
        run: |
          cd integration_tests/pubsub_to_pubsub
          ./pubsub_integration.sh

      - name: Run Pub/Sub multi-output integration test
        run: |
          cd integration_tests/pubsub_to_pubsub_multi_output
          ./pubsub_integration.sh
